<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [10]:
import numpy as np

### Exercise 1

| Term       | Brief Description |
|------------|-------------------|
| Subsetting |*It is the process of extracting a small data set from a bigger one, like taking a subset from a set. Indexing and Slicing counts as subsetting!*                    |
| Indexing   |Picking a certain item from the list. *It refers one element!*                   |
| Slicing    |Cutting a list like with a knife, so you have a range of items in the same order as previously in the set. *Method to take sub-sequence from larger sequence*                    |
| Masking    |*Analyzing data in arrays, like making a separate list of true's and false's for a certain criteria in the original array and then using that separate list to filter/do other operations to the original list.*                     |

### Exercise 2

In [35]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
numbers = np_array_2d[:,0]
alphabets = np_array_2d[:,1]
print(numbers)

integ = numbers.astype(int)

mod = integ%2

faltru = mod == 1

final = []
for i in range(len(integ)):
    if faltru[i] == True:
        final.append(alphabets[i])
    else:
        continue

print(final)

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']
[np.str_('A'), np.str_('C'), np.str_('E'), np.str_('G'), np.str_('I')]


In [36]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
numbers = np_array_2d[:,0]
alphabets = np_array_2d[:,1]
print(numbers)

integ = numbers.astype(int)

mod = integ%2

faltru = mod == 1

final = alphabets[faltru]

print(final)

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']
['A' 'C' 'E' 'G' 'I']


### Exercise 3

In [ ]:
digits = [[66, 50, 57, -1, -1],
          [92, -1, 88, -1, -1],
          [75, -1, -1, 76, -1],
          [-1, 51, 87, -1, -1],
          [71, -1, 67, -1, 69]]

dig=np.array(digits)

for i in range(len(digits)):
    integ_i=(dig[i][:]).astype(int)
    print(integ_i)
    trufal_i=integ_i>50
    faltru_i=integ_i==50

final_0=[]
final_1=[]
final_2=[]
final_3=[]
final_4=[]

for i in range(len(digits)):
    for j in range(0,5):
        if faltru_i[j] == True:
            final_i[j]=0
        elif trufal_i[j] == True:
            print(i)
            print(j)
            globals()[f"final_{i}"][j]=1
        else:
            final_i[j]=-1

print(final)

# i give up on this method, just ignore this one

[66 50 57 -1 -1]
[92 -1 88 -1 -1]
[75 -1 -1 76 -1]
[-1 51 87 -1 -1]
[71 -1 67 -1 69]
0
0


IndexError: list assignment index out of range

In [26]:
dig = np.array(digits)

dig[dig < 50] = -1
dig[dig > 50] = 1
dig[dig == 50] = 0

print(dig)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
